# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptocurrencyAnalizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptocurrencyAnalizer
  pod 'AFNetworking', '~> 4.0'
  pod 'CorePlot', '~> 2.3'
  pod 'FMDB'
end
